
--lwk made gpt manually categorize all these clubs... issue that if a new club is added it wont be categorized... fix later
alter table organizations add column if not exists is_student_org boolean not null default true;
create index if not exists organizations_category_idx on organizations (category);

update organizations set category = 'academic', is_student_org = false, is_active = false where slug in ('biomedical-biological-sciences', 'biomedical-engineering', 'cheme7900-seminar-series', 'cornell-reproductive-sciences', 'german-studies');
update organizations set category = 'academic', is_student_org = true, is_active = true where slug in ('american-meteorological-society-at-cornell-chapter', 'bee-hive-society-of-biological-and-environmental-engineering', 'biomedical-engineering-society', 'biomedical-engineering-women-s-group', 'cems-club-usa', 'chemistry-peer-advisors-at-cornell', 'cornell-advancing-science-and-policy-club', 'cornell-astronomical-society', 'cornell-energy-club', 'cornell-undergraduate-research-board', 'cryosphere-community-at-cornell', 'cyber-security-club-at-cornell', 'economics-society-at-cornell', 'food-science-club', 'food-science-product-development-club', 'global-health-student-advisory-board', 'herpetological-society-at-cornell', 'hortus-forum-undergraduate-horticulture-club', 'hydroponics-at-cornell', 'international-affairs-society-at-cornell', 'logos-the-cornell-undergraduate-philosophy-club-and-journal', 'mass-spectrometry-student-society-at-cornell', 'society-of-physics-students', 'steminist-movement-at-cornell', 'the-responsible-artificial-intelligence-network', 'undergraduate-biomedical-engineering-society-at-cornell', 'women-in-computing-at-cornell');
update organizations set category = 'campus', is_student_org = false, is_active = false where slug in ('campusgroups-testgroup-for-features', 'che-student-services', 'class-notes', 'cooperative-extension', 'cornell-housing-off-campus-resources-support', 'cornell-institute-for-food-systems', 'cti-all', 'cti-faculty', 'cti-grad-students', 'dyson-office-of-diversity-and-inclusion', 'office-of-academic-discovery-and-impact', 'office-of-inclusive-excellence', 'translator-interpreter-program', 'working-at-cornell');
update organizations set category = 'campus', is_student_org = false, is_active = true where slug in ('big-red-barn', 'campus-activities', 'campus-sustainability-office', 'cornell-career-network', 'cornell-cinema', 'cornell-department-of-music', 'cornell-equine-park', 'cornell-events', 'cornell-health', 'cornell-lab-of-ornithology', 'cornell-outdoor-education', 'cornell-physical-education-and-recreation', 'cu-library', 'department-of-architecture', 'department-of-performing-and-media-arts', 'gender-equity-resource-center', 'global-cornell', 'language-expansion-program', 'latina-o-studies-program-lsp-student-success-office', 'lgbt-resource-center', 'office-of-spirituality-and-meaning-making', 'parker-center-for-investment-research');
update organizations set category = 'campus', is_student_org = true, is_active = true where slug in ('cornell-university-class-councils', 'cu-tonight-commission', 'cupb-cornell-university-program-board');
update organizations set category = 'cultural', is_student_org = true, is_active = true where slug in ('american-indian-science-and-engineering-society', 'armenian-student-organization', 'bangladeshi-students-association', 'black-student-empowerment', 'black-students-united', 'chinese-students-and-scholars-association-at-cornell', 'chinese-students-association', 'contigo-peru', 'east-african-students-together', 'ghanaians-at-cornell', 'haitian-students-association', 'hong-kong-student-association', 'india-association-at-cornell-university', 'minorities-in-agriculture-natural-resources-and-related-sciences', 'movimiento-estudiantil-chican-at-de-aztlan', 'native-american-and-indigenous-students-at-cornell', 'pakistani-students-association', 'proyecto-palante', 'society-for-india', 'soulaan-nation', 'taiwanese-american-student-association-at-cornell');
update organizations set category = 'gaming', is_student_org = true, is_active = true where slug in ('cornell-brawl-stars-club', 'fighting-game-club-at-cornell', 'gaming-at-cornell', 'super-smash-brothers-club-at-cornell', 'vet-tabletop-vets');
update organizations set category = 'graduate', is_student_org = true, is_active = true where slug in ('american-society-of-landscape-architects-cornell-graduate-chapter', 'biochemistry-molecular-and-cell-biology-graduate-student-association', 'black-in-public-policy', 'chemical-engineering-graduate-student-association-chegsa', 'communication-graduate-student-association', 'cornell-turkish-graduate-student-association', 'food-science-graduate-student-organization', 'genetics-genomics-development-graduate-student-association', 'graduate-and-professional-student-assembly', 'graduate-student-association-for-economics', 'graduate-student-school-outreach-program', 'graduate-students-in-public-policy', 'graduate-women-in-science', 'indigenous-graduate-student-association', 'international-graduate-and-professional-students-organization', 'korean-graduate-student-association', 'latine-graduate-student-coalition', 'law-american-constitution-society-the-cornell-law-school-student-chapter', 'law-black-law-students-association', 'law-briggs-society-of-international-law', 'law-business-law-society', 'law-california-law-students-association', 'law-cornell-middle-eastern-and-north-african-law-students-association', 'law-federalist-society-at-cornell', 'law-first-generation-student-association', 'law-korea-law-and-culture-society', 'law-veteran-student-association-at-cornell-law', 'law-women-of-color-collective', 'mac-doctoral-peer-mentoring-club', 'medieval-studies-graduate-association', 'physics-graduate-society', 'plant-biology-graduate-student-association', 'sages-student-association-of-the-geneva-experiment-station', 'vc-johnson', 'vet-american-association-of-equine-practitioners-student-chapter', 'vet-american-association-of-small-ruminant-practitioners-student-chapter', 'vet-american-veterinary-society-of-animal-behavior-student-chapter', 'vet-association-for-non-traditional-students-at-cornell-college-of-veterinary-me', 'vet-association-of-veterinary-scientists', 'vet-cvm-peer-mentors', 'vet-shelter-medicine-club', 'vet-small-animal-clinical-skills-club', 'vet-the-association-of-asian-veterinary-medical-professionals-at-cornell', 'vet-zoo-and-wildlife-society', 'women-in-public-policy', 'zoo-exotics-wildlife-medicine-at-cornell');
update organizations set category = 'greek', is_student_org = true, is_active = true where slug in ('axsigma-alpha-chi-sigma', 'beta-alpha-psi', 'delta-kappa-alpha-professional-cinematic-society', 'epsilon-nu-tau', 'lambda-theta-phi');
update organizations set category = 'interest', is_student_org = true, is_active = true where slug in ('birding-club-at-cornell', 'cornell-amateur-radio-club', 'cornell-anime-club', 'cornell-coffee-club', 'cornell-fanworks-club', 'eta-club-at-cornell', 'mastering-unique-nutritious-culinary-hacks-at-cornell', 'quiz-bowl-club-cornell', 'rainy-day', 'snail-mail-club-at-cornell');
update organizations set category = 'media', is_student_org = true, is_active = true where slug in ('big-red-vision');
update organizations set category = 'performing-arts', is_student_org = true, is_active = true where slug in ('bhangra-at-cornell', 'cornell-contra-dance-club', 'dancer-s-alliance-at-cornell', 'dancesport-at-cornell', 'grad-student-improv-club', 'guild-of-visual-arts', 'impact-dance-troupe', 'jazzplus', 'khiladi-at-cornell', 'loko', 'nazaqat', 'quodlibet', 'salsa-pa-lante-casineros-at-cornell', 'shadows-dance-troupe', 'society-for-the-promotion-of-indian-classical-music-and-culture-amongst-youth', 'swing-syndicate-at-cornell', 'taiko-at-cornell', 'tango-at-cornell', 'vet-ultrasound-a-cappella');
update organizations set category = 'political', is_student_org = true, is_active = true where slug in ('alexander-hamilton-society', 'coalition-for-de-polarization-at-cornell', 'college-republicans-at-cornell', 'cornell-votes');
update organizations set category = 'pre-professional', is_student_org = true, is_active = true where slug in ('air-and-sea-hospitality', 'american-hotel-and-lodging-association-student-chapter-at-cornell-university', 'american-society-of-mechanical-engineers-at-cornell-university-chapter', 'dietetics-association-at-cornell-university', 'eng-society-of-asian-scientists-and-engineers-at-cornell', 'institute-of-electrical-and-electronics-engineers-ieee', 'korean-business-association', 'med-in-black-association', 'mosaic-hospitality-association', 'mu-epsilon-delta', 'pre-dental-society-at-cornell', 'pre-veterinary-society', 'society-of-women-engineers-at-cornell-university', 'women-s-leadership-initiative-at-cornell');
update organizations set category = 'project-team', is_student_org = true, is_active = true where slug in ('cornell-assistive-technologies-project-team');
update organizations set category = 'religious', is_student_org = false, is_active = true where slug in ('collis-institute-for-catholic-thought-and-culture', 'the-thomistic-institute-at-cornell-university');
update organizations set category = 'religious', is_student_org = true, is_active = true where slug in ('cornell-catholic-graduate-and-professional-student-group', 'cru', 'graduate-christian-fellowship-at-cornell', 'hindu-student-council', 'hindu-yuva-at-cornell', 'jewish-graduate-student-association', 'protestant-cooperative-ministry-at-cornell', 'sephardi-mizrahi-student-council', 'sikh-students-association', 'the-chavurah-at-cornell', 'the-episcopal-church-at-cornell');
update organizations set category = 'residential', is_student_org = false, is_active = true where slug in ('akwe-kon', 'alice-cook-house', 'balch-hall', 'barbara-mcclintock-hall', 'carl-becker-house', 'court-kay-bauer-hall', 'flora-rose-house', 'gan-dag-hall', 'hans-a-bethe-house', 'holland-international-living-center', 'latino-living-center', 'mary-donlon-hall', 'mews-and-loving-house-the-lgbtq-living-learning-unit', 'north-campus-faculty-living-learning-programs', 'toni-morrison-hall', 'wanawake-wa-wari-cooperative', 'william-keeton-house');
update organizations set category = 'service', is_student_org = true, is_active = true where slug in ('animal-advocacy-at-cornell', 'association-for-students-and-community', 'big-red-buddies', 'circle-k-at-cornell', 'computer-reuse-association-at-cornell', 'cornell-hunger-relief-program', 'dilmun-hill-student-farm', 'encouraging-young-engineers-and-scientists', 'homelessness-action-project-at-cornell', 'kidney-disease-screening-and-awareness-program', 'knit-with-care', 'let-s-get-ahead-at-cornell', 'student-neurodiversity-alliance-at-cornell');
update organizations set category = 'sports', is_student_org = true, is_active = true where slug in ('bowling-club-at-cornell', 'dragon-boat-club-at-cornell', 'footvolley-at-cornell', 'karate-club-at-cornell', 'kendo-club-at-cornell-university', 'pole-posse', 'running-club-at-cornell', 'table-tennis-club-at-cornell', 'women-s-ice-hockey-club-at-cornell');
