insert into organizations (slug, name, category, website_url, is_student_org, is_active)
values
  ('aguaclara', 'AguaClara', 'project-team', 'https://aguaclara.cornell.edu/', true, true),
  ('combat-robotics-at-cornell', 'Combat Robotics at Cornell', 'project-team', 'https://combatrobotics.engineering.cornell.edu/', true, true),
  ('cornell-appdev', 'Cornell AppDev', 'project-team', 'https://www.cornellappdev.com/', true, true),
  ('cornell-assistive-technologies-project-team', 'Cornell Assistive Technologies Project Team', 'project-team', 'https://www.cornellassist.com/', true, true),
  ('cu-sail', 'CU Sail', 'project-team', 'https://cusail.com/', true, true),
  ('cornell-baja-racing', 'Cornell Baja Racing', 'project-team', 'https://baja.mae.cornell.edu/', true, true),
  ('cornell-biomedical-device', 'Cornell Biomedical Device', 'project-team', 'https://www.cubmd.org/', true, true),
  ('cornell-cheme-car', 'Cornell ChemE Car', 'project-team', 'https://cornellchemecar.com/', true, true),
  ('cornell-concrete-canoe', 'Cornell Concrete Canoe', 'project-team', 'https://cornellconcretecanoe.com/', true, true),
  ('cornell-custom-silicon-systems', 'Cornell Custom Silicon Systems', 'project-team', 'https://c2s2.engineering.cornell.edu/', true, true),
  ('cornell-data-science', 'Cornell Data Science', 'project-team', 'https://cornelldata.science/', true, true),
  ('cornell-debut', 'Cornell DEBUT', 'project-team', 'https://cornelldebut.org/', true, true),
  ('cornell-digital-tech-innovation', 'Cornell Digital Tech & Innovation', 'project-team', 'https://www.cornelldti.org/', true, true),
  ('cornell-design-build-fly', 'Cornell Design Build Fly', 'project-team', 'https://dbf.engineering.cornell.edu/', true, true),
  ('cornell-electric-vehicles', 'Cornell Electric Vehicles', 'project-team', 'https://www.cornellelectricvehicles.org/', true, true),
  ('engineering-world-health', 'Engineering World Health', 'project-team', 'https://www.cornellewh.org/', true, true),
  ('cornell-university-extended-reality', 'Cornell University Extended Reality', 'project-team', 'https://cuxr.github.io/', true, true),
  ('hack4impact-cornell', 'Hack4Impact Cornell', 'project-team', 'https://www.cornellh4i.org/', true, true),
  ('cornell-hyperloop', 'Cornell Hyperloop', 'project-team', 'https://cornellhyperloop.com/', true, true),
  ('cornell-igem', 'Cornell iGEM', 'project-team', 'https://igem.engineering.cornell.edu/', true, true),
  ('cornell-mars-rover', 'Cornell Mars Rover', 'project-team', 'https://marsrover.engineering.cornell.edu/', true, true),
  ('cornell-nexus', 'Cornell Nexus', 'project-team', 'https://www.cornellnexus.com/', true, true),
  ('cornell-fsae-racing', 'Cornell FSAE Racing', 'project-team', 'https://cornellracing.org/', true, true),
  ('cornell-rocketry', 'Cornell Rocketry', 'project-team', 'https://cornellrocketryteam.com/', true, true),
  ('cornell-salt', 'Cornell SALT', 'project-team', 'https://www.csaltcornell.org/', true, true),
  ('cornell-seismic-design', 'Cornell Seismic Design', 'project-team', 'http://cornellseismicdesign.com/', true, true),
  ('cornell-steel-bridge', 'Cornell Steel Bridge', 'project-team', 'https://steelbridge.engineering.cornell.edu/', true, true),
  ('cuauv', 'Cornell University Autonomous Underwater Vehicle', 'project-team', 'https://cuauv.org/', true, true),
  ('cuair', 'Cornell University Unmanned Air Systems', 'project-team', 'https://cuair.org/', true, true),
  ('cornell-autoboat', 'Cornell AutoBoat', 'project-team', 'https://www.cornellautoboat.com/', true, true),
  ('cu-autonomous-drone', 'CU Autonomous Drone', 'project-team', 'https://cuad.info/', true, true),
  ('cu-geodata', 'CU GeoData', 'project-team', 'https://cornellgeodata.com/', true, true),
  ('engineers-for-a-sustainable-world', 'Engineers for a Sustainable World', 'project-team', 'https://esw.engineering.cornell.edu/', true, true),
  ('engineers-in-action', 'Engineers in Action', 'project-team', 'https://eia.engineering.cornell.edu/', true, true),
  ('engineers-without-borders', 'Engineers Without Borders', 'project-team', 'https://www.ewbcornell.org/', true, true),
  ('senstech-cornell', 'SensTech Cornell', 'project-team', 'https://www.cornellsenstech.com/', true, true)
on conflict (slug) do update set
  name           = excluded.name,
  category       = excluded.category,
  website_url    = excluded.website_url,
  is_student_org = true,
  is_active      = true;

insert into sources (org_id, kind, url)
select o.id, 'website', v.url
from (values
  ('aguaclara', 'https://aguaclara.cornell.edu/Apply'),
  ('combat-robotics-at-cornell', 'https://combatrobotics.engineering.cornell.edu/#/apply'),
  ('cornell-appdev', 'https://www.cornellappdev.com/apply'),
  ('cornell-assistive-technologies-project-team', 'https://www.cornellassist.com/JoinUs'),
  ('cu-sail', 'https://cusail.com/'),
  ('cornell-baja-racing', 'https://baja.mae.cornell.edu/apply'),
  ('cornell-biomedical-device', 'https://www.cubmd.org/apply'),
  ('cornell-cheme-car', 'https://cornellchemecar.com/'),
  ('cornell-concrete-canoe', 'https://cornellconcretecanoe.com/recruitment'),
  ('cornell-custom-silicon-systems', 'https://c2s2.engineering.cornell.edu/'),
  ('cornell-data-science', 'https://cornelldata.science/recruitment'),
  ('cornell-debut', 'https://cornelldebut.org/'),
  ('cornell-digital-tech-innovation', 'https://new.cornelldti.org/apply'),
  ('cornell-design-build-fly', 'https://dbf.engineering.cornell.edu/'),
  ('cornell-electric-vehicles', 'https://www.cornellelectricvehicles.org/apply'),
  ('engineering-world-health', 'https://www.cornellewh.org/join'),
  ('cornell-university-extended-reality', 'https://cuxr.github.io/'),
  ('hack4impact-cornell', 'https://www.cornellh4i.org/work-with-us'),
  ('cornell-hyperloop', 'https://www.cornellhyperloop.com/apply.html'),
  ('cornell-igem', 'https://igem.engineering.cornell.edu/apply.html'),
  ('cornell-mars-rover', 'https://marsrover.engineering.cornell.edu/'),
  ('cornell-nexus', 'https://www.cornellnexus.com/apply'),
  ('cornell-fsae-racing', 'https://cornellracing.org/join/'),
  ('cornell-rocketry', 'https://cornellrocketryteam.com/apply'),
  ('cornell-salt', 'https://www.csaltcornell.org/apply.html'),
  ('cornell-seismic-design', 'http://cornellseismicdesign.com/'),
  ('cornell-steel-bridge', 'https://steelbridge.engineering.cornell.edu/apply.html'),
  ('cuauv', 'https://cuauv.org/apply'),
  ('cuair', 'https://cuair.org/apply.html'),
  ('cornell-autoboat', 'https://www.cornellautoboat.com/'),
  ('cu-autonomous-drone', 'https://cuad.info/'),
  ('cu-geodata', 'https://cornellgeodata.com/'),
  ('engineers-for-a-sustainable-world', 'https://esw.engineering.cornell.edu/'),
  ('engineers-in-action', 'https://eia.engineering.cornell.edu/'),
  ('engineers-without-borders', 'https://www.ewbcornell.org/'),
  ('senstech-cornell', 'https://www.cornellsenstech.com/')
) as v(slug, url)
join organizations o on o.slug = v.slug
on conflict (org_id, url) do update set is_enabled = true;

insert into events
  (org_id, source_id, external_id, title, starts_at, all_day, location, url)
select
  o.id, s.id, v.external_id, v.title,
  v.starts_at,
  v.all_day, v.location, s.url
from (values
  ('aguaclara', 'aguaclara-2026-09-16-uniform-first-offer-date-upperclassmen', 'Uniform First Offer Date (Upperclassmen)', (timestamp '2026-09-16 00:00' at time zone 'America/New_York'), true, null),
  ('aguaclara', 'aguaclara-2026-09-25-add-deadline', 'Add Deadline', (timestamp '2026-09-25 17:00' at time zone 'America/New_York'), false, null),
  ('aguaclara', 'aguaclara-2026-10-15-first-year-transfer-applications-due', 'First-Year & Transfer Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('aguaclara', 'aguaclara-2026-11-02-uniform-first-offer-date-first-year-transfer', 'Uniform First Offer Date (First-Year & Transfer)', (timestamp '2026-11-02 00:00' at time zone 'America/New_York'), true, null),
  ('aguaclara', 'aguaclara-2026-11-04-onboarding-begins', 'Onboarding Begins', (timestamp '2026-11-04 00:00' at time zone 'America/New_York'), true, null),
  ('aguaclara', 'aguaclara-2027-01-04-spring-recruiting-begins', 'Spring Recruiting Begins', (timestamp '2027-01-04 00:00' at time zone 'America/New_York'), true, null),
  ('aguaclara', 'aguaclara-2027-01-28-spring-applications-due', 'Spring Applications Due', (timestamp '2027-01-28 23:59' at time zone 'America/New_York'), false, null),
  ('aguaclara', 'aguaclara-2027-02-10-spring-uniform-first-offer-date', 'Spring Uniform First Offer Date', (timestamp '2027-02-10 00:00' at time zone 'America/New_York'), true, null),
  ('aguaclara', 'aguaclara-2027-02-19-spring-add-deadline', 'Spring Add Deadline', (timestamp '2027-02-19 17:00' at time zone 'America/New_York'), false, null),
  ('combat-robotics-at-cornell', 'combat-robotics-at-cornell-2026-09-18-info-session', 'Info Session', (timestamp '2026-09-18 16:00' at time zone 'America/New_York'), false, 'Tang 203'),
  ('combat-robotics-at-cornell', 'combat-robotics-at-cornell-2026-09-26-info-session', 'Info Session', (timestamp '2026-09-26 12:00' at time zone 'America/New_York'), false, 'North Campus (TBD)'),
  ('combat-robotics-at-cornell', 'combat-robotics-at-cornell-2026-10-08-info-session', 'Info Session', (timestamp '2026-10-08 17:00' at time zone 'America/New_York'), false, 'Tang 205'),
  ('combat-robotics-at-cornell', 'combat-robotics-at-cornell-2026-10-15-applications-due', 'Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('cornell-appdev', 'cornell-appdev-2026-09-16-decisions-released-sep-16-sep-23', 'Decisions Released (Sep 16 - Sep 23)', (timestamp '2026-09-16 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-assistive-technologies-project-team', 'cornell-assistive-technologies-project-team-2026-09-13-toy-adapting-workshop-1', 'Toy Adapting Workshop 1', (timestamp '2026-09-13 16:00' at time zone 'America/New_York'), false, 'Martha Van Rensselaer Hall 1153'),
  ('cornell-assistive-technologies-project-team', 'cornell-assistive-technologies-project-team-2026-09-19-engineering-info-session-1', 'Engineering Info Session 1', (timestamp '2026-09-19 17:00' at time zone 'America/New_York'), false, 'Zoom'),
  ('cornell-assistive-technologies-project-team', 'cornell-assistive-technologies-project-team-2026-09-25-cookies-with-cat', 'Cookies with CAT', (timestamp '2026-09-25 18:00' at time zone 'America/New_York'), false, 'Upson Hall 216'),
  ('cornell-assistive-technologies-project-team', 'cornell-assistive-technologies-project-team-2026-09-26-toy-adapting-workshop-2', 'Toy Adapting Workshop 2', (timestamp '2026-09-26 15:00' at time zone 'America/New_York'), false, 'Martha Van Rensselaer Hall 1153'),
  ('cornell-assistive-technologies-project-team', 'cornell-assistive-technologies-project-team-2026-09-26-engineering-info-session-2', 'Engineering Info Session 2', (timestamp '2026-09-26 18:00' at time zone 'America/New_York'), false, 'Zoom'),
  ('cornell-assistive-technologies-project-team', 'cornell-assistive-technologies-project-team-2026-09-27-toy-adapting-workshop-3', 'Toy Adapting Workshop 3', (timestamp '2026-09-27 16:30' at time zone 'America/New_York'), false, 'Martha Van Rensselaer Hall 1153'),
  ('cornell-assistive-technologies-project-team', 'cornell-assistive-technologies-project-team-2026-09-30-business-info-session', 'Business Info Session', (timestamp '2026-09-30 17:00' at time zone 'America/New_York'), false, 'Statler Hall 291'),
  ('cornell-assistive-technologies-project-team', 'cornell-assistive-technologies-project-team-2026-10-02-engineering-info-session-3', 'Engineering Info Session 3', (timestamp '2026-10-02 17:30' at time zone 'America/New_York'), false, 'Location TBD'),
  ('cornell-assistive-technologies-project-team', 'cornell-assistive-technologies-project-team-2026-10-04-toy-adapting-workshop-4', 'Toy Adapting Workshop 4', (timestamp '2026-10-04 16:30' at time zone 'America/New_York'), false, 'Martha Van Rensselaer Hall 1153'),
  ('cornell-assistive-technologies-project-team', 'cornell-assistive-technologies-project-team-2026-10-15-first-year-transfer-applications-due', 'First-Year & Transfer Applications Due', (timestamp '2026-10-15 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-baja-racing', 'cornell-baja-racing-2026-09-29-info-session-3', 'Info Session #3', (timestamp '2026-09-29 16:30' at time zone 'America/New_York'), false, 'Location TBA'),
  ('cornell-baja-racing', 'cornell-baja-racing-2026-10-06-info-session-4', 'Info Session #4', (timestamp '2026-10-06 16:30' at time zone 'America/New_York'), false, 'Location TBA'),
  ('cornell-baja-racing', 'cornell-baja-racing-2026-10-15-first-year-transfer-applications-due', 'First-Year & Transfer Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('cornell-biomedical-device', 'cornell-biomedical-device-2026-09-21-info-session-1', 'Info Session #1', (timestamp '2026-09-21 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-biomedical-device', 'cornell-biomedical-device-2026-09-30-info-session-2', 'Info Session #2', (timestamp '2026-09-30 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-biomedical-device', 'cornell-biomedical-device-2026-10-15-freshmen-transfer-applications-due', 'Freshmen & Transfer Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('cornell-concrete-canoe', 'cornell-concrete-canoe-2026-09-16-upperclassmen-first-offer-date', 'Upperclassmen First Offer Date', (timestamp '2026-09-16 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-concrete-canoe', 'cornell-concrete-canoe-2026-10-15-first-year-transfer-applications-due', 'First-Year & Transfer Applications Due', (timestamp '2026-10-15 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-concrete-canoe', 'cornell-concrete-canoe-2026-11-02-first-year-transfer-first-offer-date', 'First-Year & Transfer First Offer Date', (timestamp '2026-11-02 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-data-science', 'cornell-data-science-2026-10-15-freshmen-transfer-applications-due', 'Freshmen & Transfer Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('cornell-electric-vehicles', 'cornell-electric-vehicles-2026-10-04-open-house', 'Open House', (timestamp '2026-10-04 16:30' at time zone 'America/New_York'), false, 'Upson B56'),
  ('cornell-electric-vehicles', 'cornell-electric-vehicles-2026-10-04-information-session-3', 'Information Session #3', (timestamp '2026-10-04 17:00' at time zone 'America/New_York'), false, 'RPCC 205'),
  ('cornell-electric-vehicles', 'cornell-electric-vehicles-2026-10-15-application-deadline', 'Application Deadline', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('engineering-world-health', 'engineering-world-health-2026-09-16-information-session', 'Information Session', (timestamp '2026-09-16 17:00' at time zone 'America/New_York'), false, 'Tang Hall 203'),
  ('engineering-world-health', 'engineering-world-health-2026-09-16-upperclassmen-final-decisions', 'Upperclassmen Final Decisions', (timestamp '2026-09-16 00:00' at time zone 'America/New_York'), true, null),
  ('engineering-world-health', 'engineering-world-health-2026-09-26-information-session', 'Information Session', (timestamp '2026-09-26 15:00' at time zone 'America/New_York'), false, 'Upson 216'),
  ('engineering-world-health', 'engineering-world-health-2026-10-05-information-session', 'Information Session', (timestamp '2026-10-05 19:00' at time zone 'America/New_York'), false, 'CIS 142'),
  ('engineering-world-health', 'engineering-world-health-2026-10-15-first-year-transfer-applications-close', 'First-Year & Transfer Applications Close', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('engineering-world-health', 'engineering-world-health-2026-11-02-first-year-transfer-final-decisions', 'First-Year & Transfer Final Decisions', (timestamp '2026-11-02 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-hyperloop', 'cornell-hyperloop-2026-10-15-first-year-transfer-applications-due', 'First-Year & Transfer Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('cornell-igem', 'cornell-igem-2026-09-28-information-session-1', 'Information Session 1', (timestamp '2026-09-28 17:00' at time zone 'America/New_York'), false, 'Tang Hall 203'),
  ('cornell-igem', 'cornell-igem-2026-10-03-demo-day', 'Demo Day', (timestamp '2026-10-03 13:00' at time zone 'America/New_York'), false, 'Phillips Hall 219'),
  ('cornell-igem', 'cornell-igem-2026-10-09-information-session-2', 'Information Session 2', (timestamp '2026-10-09 17:00' at time zone 'America/New_York'), false, 'Upson Hall 216'),
  ('cornell-nexus', 'cornell-nexus-2026-09-14-electrical-workshop-circuits-breadboarding-sep-14-20', 'Electrical Workshop: Circuits + Breadboarding (Sep 14 - 20)', (timestamp '2026-09-14 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-nexus', 'cornell-nexus-2026-09-14-information-session', 'Information Session', (timestamp '2026-09-14 20:00' at time zone 'America/New_York'), false, null),
  ('cornell-nexus', 'cornell-nexus-2026-09-16-uniform-first-offer-date-upperclassmen', 'Uniform First Offer Date (Upperclassmen)', (timestamp '2026-09-16 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-nexus', 'cornell-nexus-2026-09-21-software-workshop-computer-vision-sep-21-27', 'Software Workshop: Computer Vision (Sep 21 - 27)', (timestamp '2026-09-21 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-nexus', 'cornell-nexus-2026-09-29-information-session', 'Information Session', (timestamp '2026-09-29 17:00' at time zone 'America/New_York'), false, null),
  ('cornell-nexus', 'cornell-nexus-2026-10-08-information-session', 'Information Session', (timestamp '2026-10-08 17:00' at time zone 'America/New_York'), false, null),
  ('cornell-nexus', 'cornell-nexus-2026-10-15-first-year-transfer-applications-due', 'First-Year & Transfer Applications Due', (timestamp '2026-10-15 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-nexus', 'cornell-nexus-2026-11-02-uniform-first-offer-date-first-year-transfer', 'Uniform First Offer Date (First-Year & Transfer)', (timestamp '2026-11-02 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-nexus', 'cornell-nexus-2026-11-04-onboarding-begins', 'Onboarding Begins', (timestamp '2026-11-04 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-fsae-racing', 'cornell-fsae-racing-2026-09-17-info-session', 'Info Session', (timestamp '2026-09-17 17:00' at time zone 'America/New_York'), false, 'Hollister Hall 401'),
  ('cornell-fsae-racing', 'cornell-fsae-racing-2026-09-29-info-session', 'Info Session', (timestamp '2026-09-29 17:00' at time zone 'America/New_York'), false, 'Hollister Hall 206'),
  ('cornell-fsae-racing', 'cornell-fsae-racing-2026-10-05-info-session', 'Info Session', (timestamp '2026-10-05 17:00' at time zone 'America/New_York'), false, 'Phillips Hall 407'),
  ('cornell-fsae-racing', 'cornell-fsae-racing-2026-10-15-first-year-transfer-applications-due', 'First-Year & Transfer Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('cornell-rocketry', 'cornell-rocketry-2026-09-24-information-session-3', 'Information Session #3', (timestamp '2026-09-24 18:00' at time zone 'America/New_York'), false, 'Tang 203'),
  ('cornell-rocketry', 'cornell-rocketry-2026-10-06-information-session-4', 'Information Session #4', (timestamp '2026-10-06 18:00' at time zone 'America/New_York'), false, 'Tang 203'),
  ('cornell-rocketry', 'cornell-rocketry-2026-10-15-first-year-transfer-applications-due', 'First-Year & Transfer Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('cornell-salt', 'cornell-salt-2026-09-23-info-session-2', 'Info Session #2', (timestamp '2026-09-23 17:00' at time zone 'America/New_York'), false, 'Hollister 366'),
  ('cornell-salt', 'cornell-salt-2026-10-08-info-session-3', 'Info Session #3', (timestamp '2026-10-08 17:00' at time zone 'America/New_York'), false, 'Upson 202'),
  ('cornell-salt', 'cornell-salt-2026-10-15-first-year-transfer-applications-due', 'First-Year & Transfer Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('cuauv', 'cuauv-2026-09-17-info-session-2', 'Info Session 2', (timestamp '2026-09-17 18:00' at time zone 'America/New_York'), false, 'Gates Hall G01'),
  ('cuauv', 'cuauv-2026-09-23-info-session-3', 'Info Session 3', (timestamp '2026-09-23 18:00' at time zone 'America/New_York'), false, 'Gates Hall G01'),
  ('cuauv', 'cuauv-2026-10-03-drive-the-sub', 'Drive The Sub', (timestamp '2026-10-03 00:00' at time zone 'America/New_York'), true, 'Teagle Pool'),
  ('cuauv', 'cuauv-2026-10-07-info-session-4', 'Info Session 4', (timestamp '2026-10-07 18:00' at time zone 'America/New_York'), false, 'Gates Hall G01'),
  ('cuauv', 'cuauv-2026-10-15-freshman-transfer-applications-due', 'Freshman & Transfer Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('cuair', 'cuair-2026-09-14-info-session-2', 'Info Session #2', (timestamp '2026-09-14 19:30' at time zone 'America/New_York'), false, 'RPCC 205'),
  ('cuair', 'cuair-2026-09-22-info-session-3', 'Info Session #3', (timestamp '2026-09-22 17:30' at time zone 'America/New_York'), false, 'Gates 114'),
  ('cuair', 'cuair-2026-09-30-women-of-cuair-panel', 'Women of CUAir Panel', (timestamp '2026-09-30 18:00' at time zone 'America/New_York'), false, 'Gates 114'),
  ('cuair', 'cuair-2026-10-03-info-session-4', 'Info Session #4', (timestamp '2026-10-03 15:00' at time zone 'America/New_York'), false, 'RPCC 205'),
  ('cuair', 'cuair-2026-10-08-info-session-5', 'Info Session #5', (timestamp '2026-10-08 17:00' at time zone 'America/New_York'), false, 'Gates 114'),
  ('cuair', 'cuair-2026-10-15-applications-due', 'Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('cuair', 'cuair-2026-11-02-offers-sent', 'Offers Sent', (timestamp '2026-11-02 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-cheme-car', 'cornell-cheme-car-2026-09-15-info-session', 'Info Session', (timestamp '2026-09-15 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-cheme-car', 'cornell-cheme-car-2026-09-16-upperclassmen-offer-day', 'Upperclassmen Offer Day', (timestamp '2026-09-16 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-cheme-car', 'cornell-cheme-car-2026-09-24-info-session', 'Info Session', (timestamp '2026-09-24 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-cheme-car', 'cornell-cheme-car-2026-10-06-resume-review', 'Resume Review', (timestamp '2026-10-06 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-cheme-car', 'cornell-cheme-car-2026-10-13-freshmen-transfer-applications-due', 'Freshmen & Transfer Applications Due', (timestamp '2026-10-13 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-cheme-car', 'cornell-cheme-car-2026-10-24-interviews-oct-24-25', 'Interviews (Oct 24 - 25)', (timestamp '2026-10-24 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-cheme-car', 'cornell-cheme-car-2026-11-02-freshmen-transfer-offer-day', 'Freshmen & Transfer Offer Day', (timestamp '2026-11-02 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-custom-silicon-systems', 'cornell-custom-silicon-systems-2026-10-15-freshmen-transfer-applications-due', 'Freshmen & Transfer Applications Due', (timestamp '2026-10-15 00:00' at time zone 'America/New_York'), true, null),
  ('cu-autonomous-drone', 'cu-autonomous-drone-2026-09-24-information-session', 'Information Session', (timestamp '2026-09-24 20:00' at time zone 'America/New_York'), false, 'Upson 206'),
  ('cu-autonomous-drone', 'cu-autonomous-drone-2026-10-08-information-session', 'Information Session', (timestamp '2026-10-08 19:00' at time zone 'America/New_York'), false, 'RPCC 205'),
  ('cu-geodata', 'cu-geodata-2026-09-16-info-session', 'Info Session', (timestamp '2026-09-16 17:00' at time zone 'America/New_York'), false, 'Snee 1150'),
  ('cu-geodata', 'cu-geodata-2026-09-16-upperclassmen-first-offer-date', 'Upperclassmen First Offer Date', (timestamp '2026-09-16 00:00' at time zone 'America/New_York'), true, null),
  ('cu-geodata', 'cu-geodata-2026-09-25-add-deadline', 'Add Deadline', (timestamp '2026-09-25 17:00' at time zone 'America/New_York'), false, null),
  ('cu-geodata', 'cu-geodata-2026-10-15-first-year-transfer-applications-due', 'First-Year & Transfer Applications Due', (timestamp '2026-10-15 23:59' at time zone 'America/New_York'), false, null),
  ('cu-geodata', 'cu-geodata-2026-10-16-interviews-oct-16-nov-1', 'Interviews (Oct 16 - Nov 1)', (timestamp '2026-10-16 00:00' at time zone 'America/New_York'), true, null),
  ('cu-geodata', 'cu-geodata-2026-11-02-first-offer-date', 'First Offer Date', (timestamp '2026-11-02 00:00' at time zone 'America/New_York'), true, null),
  ('cu-geodata', 'cu-geodata-2026-11-04-onboarding-begins', 'Onboarding Begins', (timestamp '2026-11-04 00:00' at time zone 'America/New_York'), true, null),
  ('cornell-autoboat', 'cornell-autoboat-2026-09-13-info-session', 'Info Session', (timestamp '2026-09-13 16:00' at time zone 'America/New_York'), false, 'Hollister 362'),
  ('cornell-autoboat', 'cornell-autoboat-2026-10-04-info-session', 'Info Session', (timestamp '2026-10-04 16:00' at time zone 'America/New_York'), false, 'Upson 206')
) as v(slug, external_id, title, starts_at, all_day, location)
join organizations o on o.slug = v.slug
join sources s on s.org_id = o.id and s.kind = 'website'
on conflict (source_id, external_id) do update set
  title        = excluded.title,
  starts_at    = excluded.starts_at,
  all_day      = excluded.all_day,
  location     = excluded.location,
  url          = excluded.url,
  last_seen_at = now(),
  updated_at   = now();
